### PR TITLE
Latest master from upstream

### PR DESCRIPTION
**Pull request by pombredanne**

### CODE REVIEW

**Comment by pombredanne** [comment]
@sigmavirus24 Thanks Ian!

**Comment by sigmavirus24** [comment]
@pombredanne why are you maintaining a fork with no differences?

**Comment by pombredanne** [comment]
@sigmavirus24 Yes Ian: a mirror. I am doing keeping this for all the code I use (and a few more) ;)
Some repos have the bad habit to disappear at times. (unlikely with you though! ;) )

**Comment by sigmavirus24** [comment]
@pombredanne so,
1. You don't need to do PRs for this
2. You don't need to thank me each time you update it

That aside, I can't exactly blame you for wanting mirrors.

**Pull request merged**
